import ROOT

file0 = ROOT.TFile.Open("/data/ncsmith/932phoID_round4/GJets.root")
file1 = ROOT.TFile.Open("/data/ncsmith/932phoID_descope/GJets.root")
t1 = file0.Get("ntupler/photons")
t2 = file1.Get("ntupler/photons")
t1.SetLineColor(ROOT.kRed)
t1.SetWeight(t2.GetEntries()*1./t1.GetEntries())

preselection = "localReco_nLayers >= 5 && abs(localReco_depthCompatibility) < 20. && localReco_seedEnergyFH/localReco_seedEnergyEE < 20. &&"

t1.Draw("localReco_sigmaVV>>ha(100,0.5,1)", preselection+"localReco_pt>25 && localReco_iGen>=0 && gen_id[localReco_iGen] == 22 && gen_isPromptFinalState[localReco_iGen]", "histex0")
t2.Draw("localReco_sigmaVV>>hb(100,0.5,1)", preselection+"localReco_pt>25 && localReco_iGen>=0 && gen_id[localReco_iGen] == 22 && gen_isPromptFinalState[localReco_iGen]", "samehistex0")
t1.Draw("localReco_sigmaVV>>hc(100,0.5,1)", preselection+"localReco_pt>25 && !(localReco_iGen>=0 && gen_id[localReco_iGen] == 22 && gen_isPromptFinalState[localReco_iGen])", "samehistex0")
t2.Draw("localReco_sigmaVV>>hd(100,0.5,1)", preselection+"localReco_pt>25 && !(localReco_iGen>=0 && gen_id[localReco_iGen] == 22 && gen_isPromptFinalState[localReco_iGen])", "samehistex0")
ROOT.gDirectory.Get("ha").SetTitle("Signal, nominal configuration")
ROOT.gDirectory.Get("hb").SetTitle("Signal, descoped 18 layer EE")
ROOT.gDirectory.Get("hc").SetTitle("Bkg., nominal configuration")
ROOT.gDirectory.Get("hd").SetTitle("Bkg., descoped 18 layer EE")
ROOT.gDirectory.Get("hc").SetLineStyle(ROOT.kDashed)
ROOT.gDirectory.Get("hd").SetLineStyle(ROOT.kDashed)
l = ROOT.gPad.BuildLegend()
l.SetHeader("#gamma+jets, p_{T}^{#gamma} > 25 GeV")
ROOT.gPad.Print("descope_sigmaVV.root")

t1.Draw("localReco_depthCompatibility>>ha(100,-5,10)", preselection+"localReco_pt>25 && localReco_iGen>=0 && gen_id[localReco_iGen] == 22 && gen_isPromptFinalState[localReco_iGen]", "histex0")
t2.Draw("localReco_depthCompatibility>>hb(100,-5,10)", preselection+"localReco_pt>25 && localReco_iGen>=0 && gen_id[localReco_iGen] == 22 && gen_isPromptFinalState[localReco_iGen]", "samehistex0")
t1.Draw("localReco_depthCompatibility>>hc(100,-5,10)", preselection+"localReco_pt>25 && !(localReco_iGen>=0 && gen_id[localReco_iGen] == 22 && gen_isPromptFinalState[localReco_iGen])", "samehistex0")
t2.Draw("localReco_depthCompatibility>>hd(100,-5,10)", preselection+"localReco_pt>25 && !(localReco_iGen>=0 && gen_id[localReco_iGen] == 22 && gen_isPromptFinalState[localReco_iGen])", "samehistex0")
ROOT.gDirectory.Get("ha").SetTitle("Signal, nominal configuration")
ROOT.gDirectory.Get("hb").SetTitle("Signal, descoped 18 layer EE")
ROOT.gDirectory.Get("hc").SetTitle("Bkg., nominal configuration")
ROOT.gDirectory.Get("hd").SetTitle("Bkg., descoped 18 layer EE")
ROOT.gDirectory.Get("hc").SetLineStyle(ROOT.kDashed)
ROOT.gDirectory.Get("hd").SetLineStyle(ROOT.kDashed)
l = ROOT.gPad.BuildLegend()
l.SetHeader("#gamma+jets, p_{T}^{#gamma} > 25 GeV")
ROOT.gPad.Print("descope_depthCompatibility.root")

t1.Draw("localReco_nLayers>>ha(50,0,50)", preselection+"localReco_pt>25 && localReco_iGen>=0 && gen_id[localReco_iGen] == 22 && gen_isPromptFinalState[localReco_iGen]", "histex0")
t2.Draw("localReco_nLayers>>hb(50,0,50)", preselection+"localReco_pt>25 && localReco_iGen>=0 && gen_id[localReco_iGen] == 22 && gen_isPromptFinalState[localReco_iGen]", "samehistex0")
t1.Draw("localReco_nLayers>>hc(50,0,50)", preselection+"localReco_pt>25 && !(localReco_iGen>=0 && gen_id[localReco_iGen] == 22 && gen_isPromptFinalState[localReco_iGen])", "samehistex0")
t2.Draw("localReco_nLayers>>hd(50,0,50)", preselection+"localReco_pt>25 && !(localReco_iGen>=0 && gen_id[localReco_iGen] == 22 && gen_isPromptFinalState[localReco_iGen])", "samehistex0")
ROOT.gDirectory.Get("ha").SetTitle("Signal, nominal configuration")
ROOT.gDirectory.Get("hb").SetTitle("Signal, descoped 18 layer EE")
ROOT.gDirectory.Get("hc").SetTitle("Bkg., nominal configuration")
ROOT.gDirectory.Get("hd").SetTitle("Bkg., descoped 18 layer EE")
ROOT.gDirectory.Get("hc").SetLineStyle(ROOT.kDashed)
ROOT.gDirectory.Get("hd").SetLineStyle(ROOT.kDashed)
l = ROOT.gPad.BuildLegend()
l.SetHeader("#gamma+jets, p_{T}^{#gamma} > 25 GeV")
ROOT.gPad.Print("descope_nLayers.root")

